### ISSUE TITLE
The CI does not generate bundle for fork PR

### ISSUE THREAD

**Issue by skydread1** [skydread1/portfolio#66]
## Problem

On `fork` PRs, the CI does not run and therefore the js bundle and rss feed are never generated.

## Suggestion:

```yaml
on:
  push:
    branches-ignore:
      - master
  pull_request:
    types: [opened, ready_for_review, review_requested]
  pull_request_review:
    types: [submitted]
```

- on request for review/read for review: generate js and xml
- on PR approval (me): commit js and xml to branch
